version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64

archives:
  - format: tarball
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macos

changelog:
  sort: asc
